content/urls.py
import imp
from django.urls import path
from . import views
from projectapp import views as project_views


app_name = 'site_content'

urlpatterns = [
    path('wishlist/', views.user_wishlist, name='wishlist'),
    path('UserGuid_detail/', views.UserGuid_detail, name='UserGuid_detail'),
    path('comment/', views.user_comment, name='comment'),
    path('purchase/', views.purchaseProject, name="purchase"),
    path('done/', views.purchaseDone, name='done')

]

projectapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('project/', views.project_list, name='project_list'),
    path('<slug:category_slug>/', views.project_list, name='project_list_by_category'),
    path('<int:id>/<slug:slug>/', views.project_detail, name='project_detail'),
    path('search', views.search, name='search'),

]

projectsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectapp.urls')),
    path('content/',include('content.urls', namespace='site_content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/models.py
from distutils import text_file
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid

# Category class
class Category(models.Model):
    """ Category class """
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=250, unique=True)
    
    class Meta:
        ordering = ('-name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name
    
    # Defining url
    def get_absolute_url(self):
        return reverse("project_list_by_category", args=[self.slug])
    
    

# Project Description 
class ProjectDetail(models.Model):
    """ Project discription of each topic """
    # name = models.ForeignKey(Project, 
                            #  verbose_name=(""), on_delete=models.CASCADE)
    table_img = models.ImageField(("Table of content Image"), 
                                  upload_to='project_image', 
                                  height_field=None, 
                                  width_field=None)
    introduction = models.CharField(max_length=100)
    intro_desc = models.TextField(("Introduction Description"))
    
    current = models.CharField(("Current System"), max_length=100)
    current_desc = models.TextField(("Current System Description"))
    
    proposed = models.CharField(("Proposed New System"), max_length=100)
    prop_desc= models.TextField(("Proposed Description"))
    
    problem = models.CharField(("Problems Of Current System"), max_length=100)
    problem_desc = models.TextField(("Problem of current system Description"))
    
    objectives = models.CharField(("Objectives"), max_length=100)
    obj_desc = models.TextField(("Objectives Description"))
    
    # def __str__(self):
    #     return self.name
    
    

# Projec class 
class Project(models.Model):
    """ Class that would create a project file """
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='projects')
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=250, db_index=True)
    image = models.ImageField(upload_to='project_image',
                              blank=True, null=True)
    file = models.FileField(upload_to='Projects/%Y/%m/%d', 
                            blank=False, null=False)
    description = models.OneToOneField(ProjectDetail,
                                       on_delete=models.CASCADE)
                                   
    price = models.DecimalField(max_digits=10, decimal_places=2)
    old_price = models.DecimalField(("Last price"), 
                                    max_digits=10, decimal_places=2)
    rating = models.IntegerField(("Project Ratings"), default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ('-name',)
        index_together = (('id', 'slug'),)
        
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("project_detail", args=[self.id, self.slug])
    
 

projectapp/views.py
from django.core import paginator
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Project, ProjectDetail
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

        


def project_list(request, category_slug=None):
    """ 
    A fuction that would show a list of available projects 
    And project category
    """
    category = None
    categories = Category.objects.all()
    projects = Project.objects.filter(available=True)
    project_file = ProjectDetail.objects.all()
    
    # Purchase form message
    messages.add_message(request, messages.SUCCESS, "Your project topic would be sent to you via your Email Address")

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        projects = projects.filter(category=category)
  
    # PAGINATOR 
    paginator = Paginator(projects, 8) # 10 Projects in each page
    page = request.GET.get('page')
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an interger deliver the first page
        projects = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of results
        projects = paginator.page(paginator.num_pages)
        
        
    return render(request, 
                  'project/index.html',
                  {'category':category,
                  'categories':categories,
                  'projects':projects,
                  'project_file':project_file,
                  'page':page,
                  'sections':'project_list', 
                  'section':'category'})
    
    
    
def project_detail(request, id, slug):
    """ Display project's Detail """
    categories = Category.objects.all()
    project = get_object_or_404(Project,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'project/detail.html',
                  {'project':project,
                   'categories':categories,})

def index(request):
    return HttpResponse('Hello')


def search(request):
    categories = Category.objects.all()
    """ Fuction that cares about searching of a project topic """
    q=request.GET['q']
    projects = Project.objects.filter(name__icontains=q)
    available_project = Project.objects.filter(available=True)
    data = Project.objects.filter(name__icontains=q).order_by('-created')
    return render(request, 'project/search.html', {'data':data,
                                                   'available_project':available_project,
                                                   'projects':projects,
                                                   'categories':categories})
    
    

projectapp/templates/include/footer.html
    <footer class="footer" style="background-color:#343A40; color:white;">
        <div class="container">
          <div class="row">
            <div class="col-sm-6" id="sell">
              <h1>IPROJECTS</h1>
            </div>
            <div class="col-sm-6" id="sell">
              <!-- <button type="button" class="btn btn-lg btn-outline-success">Sell Project</button> -->
              <!-- <button type="button" class="btn btn-lg btn-warning">Advanced Projects</button> -->
            </div>
            <div class="col-sm-5">
              <h6>About company</h6>
              <div class="media">
                <img src="../images//cfo.jpg" class="align-self-start mr-3" alt="Not available">
                <div class="media-body">
                  <h5 class="mt-0">Top-aligned media</h5>
                  <p>I’m gon’ put her in a coma. You give a hundred reasons why, and you say you're really gonna try. So I sat quietly, agreed politely. Suiting up for my crowning battle. And on my 18th Birthday we got matching tattoos. So très chic, yeah, she's a classic. I am ready for the road less traveled.</p>
                  <p>I'm walking on air (tonight). But down to earth. You're original, cannot be replaced. But in another life I would be your girl. We drove to Cali and got drunk on the beach. We can dance, until we die, you and I, will be young forever. Saw you downtown singing the Blues.</p>
                </div>
              </div>
            </div>
            <div class="col-sm-3">
              <h5>Company in touches with</h5>
              <ul>
                <li><a href="#">Informatics Singphore</a></li>
                <li><a href="#">Mahatma Gandi University</a></li>   
                <li><a href="#">What's new</a></li>
              </ul>
            </div>
            <div class="col-sm-2">
              <h5>Help</h5>
              <ul>
                <li><a href="#">SUPPORT</a></li>
                <li><a href="{% url 'site_content:UserGuid_detail'%}">FAQs</a></li>
                <li><a href="{% url 'site_content:UserGuid_detail'%}">Buy Project</a></li>
                <li><a href="{% url 'site_content:UserGuid_detail'%}">Payment Issues</a></li>
                <li><a href="{% url 'site_content:UserGuid_detail'%}">Project Guarantee</a></li>
              </ul>
            </div>
            <div class="col-sm-2">
              <h5>Contact us</h5>
              <ul>
                <li><a style="text-decoration: none;" href="#">Facebook</a></li>
                <li><a style="text-decoration: none;" href="#">Instagram</a></li>
                <li><a style="text-decoration: none;" href="#">Email</a></li>
                <li><a style="text-decoration: none;" href="#">What's app</a></li>
              </ul>
              <p>Get exculusive resources straight to your inbox</p>
              <button type="button" class="btn btn-outline-success"><a href="#"></a>Sign up</button>
            </div>
          </div>
          <p><span>iproject.com</span> Copyright 2010-{% now "Y" %}  C-Tech company All right reserved.</p>
        </div>
      </footer>

projectapp/templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'project_list'%}">IPROJECTS <span><i class="fa fa-graduation-cap"></i></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li {% if sections == 'project_list' %}class="nav-item active"{% endif %}>
          <a class="nav-link" href="{% url 'project_list'%}">Home <span class="sr-only">(current)</span> <span><i class="fa fa-home"></i></span></a>
        </li>
        <li {% if section == 'UserGuid_detail' %}class="nav-item active"{% endif %}>
          <a class="nav-link" href="{% url 'site_content:UserGuid_detail'%}">Issues <span><i class="fa fa-question-circle"></i></span></a>
        </li>
        <li  {% if section == 'user_wishlist' %}class="nav-item active"{% endif %}>
          <a class="nav-link" href="{% url 'site_content:wishlist'%}">Wish list <span><i class="fa fa-list-alt"></i></span></a>
        </li>
        <li {% if section == 'comment' %}  class="nav-item active" {% endif %}>
          <a class="nav-link" href="{% url 'site_content:comment'%}">Comment's <span><i class="fa fa-comment"></i></span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% for category in categories %}
              <a class="dropdown-item" href="{% url 'project_list_by_category' category.slug%}">{{ category.name }}</a>
            {% endfor %} 
          </div>
        </li>
      </ul>
    <div>
    </div>
  </div>
</nav>

projectapp/templates/include/paginator.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a style="text-decoration: none;" href="?page={{ page.previous_page_number }}">
        <span><i class="fa fa-angle-double-left"></i></span> Previous</a>
    {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a style="text-decoration:none;" href="?page={{ page.next_page_number }}">Next
        <span><i class="fa fa-angle-double-right"></i></span>
    </a>
        <p></p>
    {% endif %}
    </span>
</div>