content/urls.py
import imp
from django.urls import path
from . import views
from projectapp import views as project_views


app_name = 'site_content'

urlpatterns = [
    path('wishlist/', views.user_wishlist, name='wishlist'),
    path('UserGuid_detail/', views.UserGuid_detail, name='UserGuid_detail'),
    path('comment/', views.user_comment, name='comment'),
    path('purchase/', views.purchaseProject, name="purchase"),
    path('done/', views.purchaseDone, name='done')

]

projectapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('project/', views.project_list, name='project_list'),
    path('<slug:category_slug>/', views.project_list, name='project_list_by_category'),
    path('<int:id>/<slug:slug>/', views.project_detail, name='project_detail'),
    path('search', views.search, name='search'),

]

projectsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projectapp.urls')),
    path('content/',include('content.urls', namespace='site_content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/models.py
from distutils import text_file
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid

# Category class
class Category(models.Model):
    """ Category class """
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=250, unique=True)
    
    class Meta:
        ordering = ('-name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name
    
    # Defining url
    def get_absolute_url(self):
        return reverse("project_list_by_category", args=[self.slug])
    
    

# Project Description 
class ProjectDetail(models.Model):
    """ Project discription of each topic """
    # name = models.ForeignKey(Project, 
                            #  verbose_name=(""), on_delete=models.CASCADE)
    table_img = models.ImageField(("Table of content Image"), 
                                  upload_to='project_image', 
                                  height_field=None, 
                                  width_field=None)
    introduction = models.CharField(max_length=100)
    intro_desc = models.TextField(("Introduction Description"))
    
    current = models.CharField(("Current System"), max_length=100)
    current_desc = models.TextField(("Current System Description"))
    
    proposed = models.CharField(("Proposed New System"), max_length=100)
    prop_desc= models.TextField(("Proposed Description"))
    
    problem = models.CharField(("Problems Of Current System"), max_length=100)
    problem_desc = models.TextField(("Problem of current system Description"))
    
    objectives = models.CharField(("Objectives"), max_length=100)
    obj_desc = models.TextField(("Objectives Description"))
    
    # def __str__(self):
    #     return self.name
    
    

# Projec class 
class Project(models.Model):
    """ Class that would create a project file """
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='projects')
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=250, db_index=True)
    image = models.ImageField(upload_to='project_image',
                              blank=True, null=True)
    file = models.FileField(upload_to='Projects/%Y/%m/%d', 
                            blank=False, null=False)
    description = models.OneToOneField(ProjectDetail,
                                       on_delete=models.CASCADE)
                                   
    price = models.DecimalField(max_digits=10, decimal_places=2)
    old_price = models.DecimalField(("Last price"), 
                                    max_digits=10, decimal_places=2)
    rating = models.IntegerField(("Project Ratings"), default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ('-name',)
        index_together = (('id', 'slug'),)
        
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("project_detail", args=[self.id, self.slug])
    
 

projectapp/views.py
from django.core import paginator
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Project, ProjectDetail
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

        


def project_list(request, category_slug=None):
    """ 
    A fuction that would show a list of available projects 
    And project category
    """
    category = None
    categories = Category.objects.all()
    projects = Project.objects.filter(available=True)
    project_file = ProjectDetail.objects.all()
    
    # Purchase form message
    messages.add_message(request, messages.SUCCESS, "Your project topic would be sent to you via your Email Address")

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        projects = projects.filter(category=category)
  
    # PAGINATOR 
    paginator = Paginator(projects, 8) # 10 Projects in each page
    page = request.GET.get('page')
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an interger deliver the first page
        projects = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of results
        projects = paginator.page(paginator.num_pages)
        
        
    return render(request, 
                  'project/index.html',
                  {'category':category,
                  'categories':categories,
                  'projects':projects,
                  'project_file':project_file,
                  'page':page,
                  'sections':'project_list', 
                  'section':'category'})
    
    
    
def project_detail(request, id, slug):
    """ Display project's Detail """
    categories = Category.objects.all()
    project = get_object_or_404(Project,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'project/detail.html',
                  {'project':project,
                   'categories':categories,})

def index(request):
    return HttpResponse('Hello')


def search(request):
    categories = Category.objects.all()
    """ Fuction that cares about searching of a project topic """
    q=request.GET['q']
    projects = Project.objects.filter(name__icontains=q)
    available_project = Project.objects.filter(available=True)
    data = Project.objects.filter(name__icontains=q).order_by('-created')
    return render(request, 'project/search.html', {'data':data,
                                                   'available_project':available_project,
                                                   'projects':projects,
                                                   'categories':categories})
    
    

projectapp/templates/project/detail.html
{% extends 'base.html' %}
{% block title %}project list{% endblock title %}

{% block content %}
<div class="jumbotron" style="background-color:#343A40; color:white">
  <h5>Project Preview for "{{ project.name}}"</h5>
  <p> <span class="text-muted">Created on {{ project.created }} <br> And Updated on {{ project.updated}}</span></p>
  <a href="{% url 'site_content:purchase'%}" class="btn btn-success btn-sm">Download Complete Project <span> <i class="fa fa-download"></i></span></a>
  <a href="{% url 'site_content:comment'%}" class="btn btn-dark btn-sm ">Comment <span><i class="fa fa-comment"></i></span></a>
  {% comment %} <a href="{% url 'project_share'%}" class="btn btn-primary btn-sm ">Share <span><i class="fa fa-share"></i></span></a> {% endcomment %}
</div>
    <div class="container">
        <div class="media">
            <a href="{{ project.image.url }}"><img src="{{ project.image.url }}" height="150" class="align-self-start mr-3" alt="..."></a>
            <div class="media-body">
              <h1>{{ project.name | capfirst }}</h1>
              <p class="text-muted">{{ project.category}} project <span><i class="fa fa-book fa-fw"></i></span></p>
              <h5 class="mt-0"> <b>Price ₦{{ project.price }}</b> <span class="text-muted"> <del>{{ project.old_price }}</del></span></h5>
              {% if project.rating == 1%}
                <p>
                  <b>Rating:</b>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                {% elif project.rating == 2 %}
                <b>Rating:</b>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                {% elif project.rating == 3%}
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                {% elif project.rating == 4%}
                <b>Rating:</b>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                {% elif project.rating == 5%}
                <b>Rating:</b>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                  <span><i class="fa fa-asterisk" style="color:gold"></i></span>
                {% else %}
                <b>Rating: </b>
                {% endif %}  
                </p>
              <p></p>
            </div> <!-- End of media-body div -->
          </div> <!-- End of media div -->
        
          <!-- ===================================================================================== -->
          <!-- project description  -->
          <!-- Table of content image  -->
          <p> <!-- for extra space  --> </p>
          <h1>Project Preview</h1>
          <hr>
          <p><!-- for extra space  --></p>
          <img src="{{ project.description.table_img.url }}" alt="" srcset="">
          <p> <!-- for extra space  --> </p>
          <!-- Project Introduction -->
          <h3>{{ project.description.introduction|capfirst}}</h3>
          <p style="border-left: 3px solid brown; padding-left:5px"> {{ project.description.intro_desc }}</p>
          <!-- Current system  -->
          <h3>{{ project.description.current|capfirst}}</h3>
          <p style="border-left: 3px solid brown; padding-left:5px">{{ project.description.current_desc }}</p>
          <!-- Proposed New System  -->
          <h3>{{ project.description.proposed|capfirst}}</h3>
          <p style="border-left: 3px solid brown; padding-left:5px">{{ project.description.prop_desc }}</p>
          <!-- Problem with current system -->
          <h3>{{ project.description.problem|capfirst}}</h3>
          <p style="border-left: 3px solid brown; padding-left:5px">{{ project.description.problem_desc }}</p>
          <!-- Objective of the project -->
          <h3>{{ project.description.objectives|capfirst}}</h3>
          <p style="border-left: 3px solid brown; padding-left:5px">{{ project.description.obj_desc }}</p>
          <!-- <p>{% lorem 3 b random %}</p> -->
          <p></p>
          <!-- Dowwnlaod project and comment button -->
          <a href="{% url 'site_content:purchase'%}" class="btn btn-success btn-sm">Download Complete Project <span> <i class="fa fa-download"></i></span></a>
          <a href="{% url 'site_content:comment'%}" class="btn btn-dark btn-sm ">Comment <span><i class="fa fa-comment"></i></span></a>
          <p></p>
 
    </div>
{% endblock content %}

projectapp/templates/project/index.html
{% extends 'base.html' %}
{% load static %}
{% load project_count %}
{% block title %}
    {% if category %} {{ category.name}} {% else %} Projects{% endif %}
{% endblock title %}

{% block content %}

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static '/images/image1.jpg'%}"  height="400" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Some representative placeholder content for the first slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/image5.jpg'%}" height="400" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Some representative placeholder content for the second slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static '/images/image4.jpg'%}" height="400" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </button>
  </div>
  <!-- end of carousel -->
  <div class="jumbotron border shadow">
    <div class="row">
        <div class="col-md-8 offset-2">
            <form action="/search">
               <div class="input-group">
                    <input type="text" name="q" placeholder="Search Project Topic" required
                    class="form-control form-control-lg">
                    <div class="input-group-append">
                        <button class="btn btn-dark btn-lg"> <span> <i class="fa fa-search"></i></span></button>
                    </div>
               </div>
              <p style="text-align: center;"> 
                <b>{% total_project %}</b> 
                <span class="text-muted">Project's are Available</span>
              </p>
        </div>
    </div>
</div>
  <div class="container">
    <h3> <span><i class="fa fa-hashtag"></i> </span> Categories</h3>
    <a href="{% url 'project_list'%}" class="btn btn-outline-secondary btn-sm">All Projects</a>
    {% for category in categories %}
      <a {% if section == 'category' %} class="btn btn-outline-secondary btn-sm" {% endif %} href="{{ category.get_absolute_url }}" title="{{ category.name }} project">{{ category.name }}</a>
    {% endfor %}
      <hr>
        <!-- project list  -->
          <h3 style="background-color: black; color:white; text-align:center"> {% if  category %} {{ category.name }} project's {% else %}All Projects {% endif %}</h3>
          <hr>
          <div class="row"> 
            {% for project in projects %}
            <div class="col-sm-3">
              <div class="card">
                <a href="{{ project.get_absolute_url }}">
                  <img height="100px" width="208" src="{% if project.image %} {{ project.image.url }} {% else %} {% static 'images/cfoo.jpg'%} {% endif %}">
                </a>
                <div class="card-body">
                  <p class="card-text">{{ project.name}} 
                    <span> <br> <b>₦{{ project.price}}</b></span> 
                     <del class="text-muted">{{ project.old_price }}</del>
                  </p>
                  <a href="{{ project.get_absolute_url }}" class="btn btn-secondary btn-sm" title="download project now">
                    Download <span> <i class="fa fa-download"></i></span>
                  </a>
                  <p class="card-text"><small class="text-muted">{{ project.category }} Project</small></p>
                </div>
              </div>
          </div>
          <p></p>
          {% endfor %}
          </div>
        {% include 'include/paginator.html' with page=projects%}
    </div> <!-- End of container -->
{% endblock content %}

projectapp/templates/project/search.html
{% extends 'base.html' %}
{% load static %}
{% block title  %}
    search
{% endblock title  %}

{% block content %}
  <div class="jumbotron" style=" margin-top:5%; background-color:#343A40; color:white;" >
      <h4> <span class="text-muted">You searched for</span> "{{ request.GET.q }}"</h4>
      {% if data.count == 0 %}
          No such project. We recommend you to write it in wish list <a href="{% url 'site_content:wishlist'%}">Go ahead</a>
      {% else %}
      <span class="text-muted">{{ data.count }} Project's found {{ data.name }}</span>
      {% endif %}
      <br>
      <a href="{% url 'project_list'%}" class="btn btn-success btn-sm"><span><i class="fa fa-angle-double-left"></i></span> Back to home</a>
  </div>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
    <div id="main" class="product-list">  
      {% if data.count == 0 %}
      <h3> No Project found for "{{request.GET.q}}" !!!</h3>
      {% else %}
      <h3> Available project's that are similar to "{{ request.GET.q }}"</h3>
      {% endif %}
      <hr>
            <!-- Displaying of project's -->
    <div class="row"> 
      
      {% for project in projects %}
        <div class="col-sm-3">
          <div class="card">
            <a href="{{ project.get_absolute_url }}">
              <img height="120px" width="200" src="{% if project.image %} {{ project.image.url }} {% else %} {% static 'images/cfoo.jpg'%} {% endif %}">
            </a>
            <div class="card-body">
              <p style="margin-top:0px; margin-bottom:0px;" class="card-text">{{ project.name}} 
                <span> <br> <b>₦{{ project.price }}</b> 
                  <i class="text-muted"> <del>{{ project.old_price}}</del></i>
                </span>
              </p>
              <p style="margin-top:0px; margin-bottom:0px;" class="card-text"><small class="text-muted"> {{project.category }} Project</small></p>
              <a href="{{ project.get_absolute_url }}" class="btn btn-secondary btn-sm" title="download project now">
                      Download <span> <i class="fa fa-download"></i></span>
              </a>
            </div>
          </div>
      </div>
      {% endfor %}
      </div>
      <p></p>
      <br>
    </div>
  </div>
</div>
</div>
{% endblock content %}